### ISSUE TITLE
Remove reference to randomly generated password for Sandbox signup

### ISSUE THREAD

**Issue by sarahwdev** [SUSE-Developer-Community/sandbox-welcome-content#102]
On this page: https://gettingstarted.cap.explore.suse.dev/password/

There is a reference to a randomly generated password... this is no longer part of the signup flow:

Changing your Password
**When you first create your sandbox account, you will be provided a randomly generated password.** For easier access, you will likely want to change your password to one that’s easier to remember. You can do that from the command line or from the Stratos UI.

**Comment by agracey** [comment]
The fix is actually waiting in #100 #101

**Comment by agracey** [comment]
ok, fixed
