### ISSUE TITLE
Broken link in cli.md # Next Steps

### ISSUE THREAD

**Issue by der-gabe** [SUSE-Developer-Community/sandbox-welcome-content#106]
The _[Introduction to the CLI](https://www.explore.suse.dev/platform-as-a-service/)_ document (`cli.md`) has the following text in its final section _[Next Steps](http://gettingstarted.cap.explore.suse.dev/cli/#next-steps)_ (2nd paragraph):

> This guide only covers rather basic use cases, but there are lots of sample applications on the Internet that can help you understand how to make use of Cloud Foundry’s more advanced features. We’ve pulled together a couple of pointers to our favourites on the [SUSE Developer Portal](https://www.explore.suse.dev/platform-as-a-service/).

… where the last three words link to https://www.explore.suse.dev/platform-as-a-service/ but that link's broken and only goes to a 404 error page.

I would submit a PR to fix it myself, but I don't know where the page moved or whether it still exists, at all. Maybe the text needs to be slightly rewritten?

**Comment by agracey** [comment]
Thanks for the heads up. I'll fix it this afternoon. 

The links should likely point to https://www.explore.suse.dev/application-platform/
