### ISSUE TITLE
Sandbox CF Routes are not working

### ISSUE THREAD

**Issue by ttakach** [SUSE-Developer-Community/sandbox-welcome-content#114]
I have tried every application I have pushed to the SUSE CAP Cloud Foundry instance.
None of them are accessible.  Is there something wrong with the SUSE CAP routes or DNS?

Sample error message:
404 Not Found: Requested route ('p-anxious-numbat-ga.cap.explore.suse.dev') does not exist.

**Comment by ttakach** [comment]
Just a follow up to the same issue.  If I scale an app to more than 2 instances both instances will alternatively load in the browser.  But if there is only one instance the app will not load in the browser at all.  

This will still be an issue for anyone trying the tutorials as they do not scale the first push until later in the exercises.  Plus we will max out the quotas if we have to have two instances of every app running in order to access them on the web.

**Comment by agracey** [comment]
Thank you for the heads up. I'll look in to it

**Comment by agracey** [comment]
Hey, @ttakach you should have received an email by now with more detail. 

I apologize for the timing, but we have decided that it's not possible to fix the problems in a way that gives our users the right level of service. As such, we have shut down the platform.

If you are looking for a developer experience on top of Kubernetes and like the ideas that Cloud Foundry put forward, definitely check out https://epinio.io It's taking a lot of the parts that we valued from Cloud Foundry and dropping the parts that aren't needed when Kubernetes is the underlying orchestration engine.
