### ISSUE TITLE
Stratos - CLI order

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#25]
Welcome screen has Stratos - CLI (twice), the menu on the left has CLI - Stratos.
Maybe unify the order.

**Comment by timirnich** [comment]
Not sure how to fix this since the order in the menu is done by Hugo - @agracey any ideas?

**Comment by ghost** [comment]
Text could follow the order in the menu. :)

________________________________________

**Comment by agracey** [comment]
This is controlled via the weight option at the top of the markdown file.
