### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#organizations-and-spaces - Targeting

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#29]
To switch to the “dev” space, use (colon missing)
cf target -s dev

Additional information required:
Maybe have -o org also included in cf target and then point out that within the same org it's possible to only specify the target. And if there's only one space, it is automatically selected.

**Comment by timirnich** [comment]
Added a paragraph.
