### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#tablang2 - npm install requirements

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#36]
What is required to run npm install

**Comment by timirnich** [comment]
Added a link to https://docs.npmjs.com/downloading-and-installing-node-js-and-npm. @agracey: we should check if there are instructions on how to set up a Javascript dev environment in openSUSE and/or SLE docs. Upstream docs at https://github.com/nodesource/distributions only mentions RH stuff (bummer).
