### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#tablang2 - mysample directory

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#39]
Previously nodejs_sample directory was created.

**Comment by timirnich** [comment]
Changed the cf push command to: 
cf push <app-name> --random-route
so that we can use it outside the javascript example (see my comment on #40). 

Note that this assigns an app name that doesn't have to be consistent with the local directory name, so it would have worked anyway.
