### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#tablang2 - --random-route explanation

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#40]
Maybe tell the outcome of creating a random route and have that displayed on routes: in the log part.

**Comment by timirnich** [comment]
I'll keep this for later since it requires a bit more time. @agracey: I think we should pull those two paragraphs out from the Javascript example into the main body since this information is generally relevant.

**Comment by agracey** [comment]
We should have a short code for callouts. I'll put in a separate issue for that improvement
