### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#service-marketplace - Missing colons and incomplete sentence

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#46]
To see the state (and a list of current services), **run**

and push again or **use**

To add the service and restage with any new environment variables needed.

**Comment by timirnich** [comment]
To see the state (and a list of current services), run --> there was an extra line break which I removed. 

The other two are, as far as I can tell, one sentence that wraps around the code block, which I think is fine. Keeping it that way for now. 

PR incoming
