### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#tabservice_lang2 - We and problematic parentheses

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#48]
**we** can consume

With this, **we** can expand **our**

**an** (extremely) **s**imple

**Comment by timirnich** [comment]
Not sure if this is a must-fix. Might be a matter of taste/writing style rather. Leaving it unchanged for now.

**Comment by ghost** [comment]
You better select the subject as either "you" or "we", but it should not change between paragraphs. I'm positive that "you" would be nicer in general.

It seems also to change within sentences:

Once **you** have installed the cf-cli, **we** need to log in.

**Select** the type of service **we** would like to bind to

**We** are binding to an existing Service Instance so click Bind to an Existing Service Instance and select the Service Instance **you** want to attach to.

To upgrade **our** application, first **make** a new commit

**Comment by agracey** [comment]
Let's leave this to the last go round of writing/editing. It's definitely a problem but will continue to pop  up as we are creating content

**Comment by agracey** [comment]
dup #70 + already fixed
