### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#debugging - We and errors

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#49]
**We**’ve already

logging, **this** is (which)

vend**e**rs

leaves **us**

**we** need

**Comment by timirnich** [comment]
Didn't understand what to change for some of these but addressed those where I did. PR incoming.

**Comment by ghost** [comment]
we...us vs you (in general throughout the pages)

venders -> vendors

logging, this is -> logging, which is
