### ISSUE TITLE
https://gettingstarted.trial.cap.suse.dev/cli/#clean-up - We and prompting

### ISSUE THREAD

**Issue by ghost** [SUSE-Developer-Community/sandbox-welcome-content#51]
**we** can delete 

cf delete <app name> (Will prompt for Yes anyway)

**Comment by timirnich** [comment]
Not sure if I understand what to do here. Might have been edited already?

**Comment by ghost** [comment]
Again in general:
we vs you 
Sometimes there read: We installed, other times you installed.
I would unify the material either for **you** or **we**.

cf delete without -f will prompt you for the deletion. 
So the wording was not exactly correct, even though
other prompts in some situations might exist.

I'll try to be more clear next time. 
I did not  explain the we thing on every issue, because
I thought there's only one person to modify. :)

**Comment by timirnich** [comment]
Done, PR incoming.
