### ISSUE TITLE
https://gettingstarted.cap.explore.suse.dev/ - TODO: At this point the reader probably wonders how this impacts debugging...

### ISSUE THREAD

**Issue by CbranSUSE** [SUSE-Developer-Community/sandbox-welcome-content#55]
I found an awesome video from the CF summit: https://www.youtube.com/watch?v=mjxE9Rb6JDU Allthough this isn't SUSE content it seems neutral enough, coming from the CF summit

If we start linking "external" content to the page, we can show openness and maybe even get external developers to guest author, or it can just help us make connections in the community

**Comment by agracey** [comment]
I think that this section should be dropped out of this page. It's already discussed in more detail on the CLI page (which is where it's more important and relevant). Thoughts?

**Comment by CbranSUSE** [comment]
reviewed and agreed.
