### ISSUE TITLE
cfcli/cleanup.md: additional items to clean up

### ISSUE THREAD

**Issue by btat** [SUSE-Developer-Community/sandbox-welcome-content#8]
Using this as a placeholder for any other things that need to be cleaned

1. Routes

If an app is deleted using `cf delete <app name>` the route created for the app will still persist.

To delete the route as well use `-r`, e.g. `cf delete -r <app name>`

If the route is not removed when the app is deleted, it can then be deleted afterwards with `cf delete-route <domain> -n <host>`. To bulk delete any routes that are not mapped in the current space use `cf delete-orphaned-routes`.

**Comment by timirnich** [comment]
Awesome @btat I've added this in a bulk PR that I'm about to push. Thanks!
