### ISSUE TITLE
link not working on: https://gettingstarted.cap.explore.suse.dev/password/

### ISSUE THREAD

**Issue by CbranSUSE** [SUSE-Developer-Community/sandbox-welcome-content#85]
_To change your password from Stratos. Log in then browse to https://stratos.cap.explore.suse.dev/user-profile/edit, enter your existing password and your new password._

https://stratos.cap.explore.suse.dev/user-profile/edit leads to 404 page

**Comment by timirnich** [comment]
It works (for me at least) when logged in, but when the user is _not_ logged in it leads to 404. I think I'll change this to telling people how to click through to the edit page since that's not totally straightforward.
